### ISSUE TITLE
Minor improvement idea

### ISSUE THREAD

**Issue by upta** [madskristensen/ResetZoom#3]
Cool idea for an extension!  I've always wondered why this wasn't just baked into VS.

Not actually an issue, but more of a query/request.  Would it be a lot of work to make the "reset" zoom value customizable?  My poor eyes don't really like 100% so I always use 110% for my VS :)

Thanks!

**Comment by madskristensen** [comment]
That's a great idea. I can do that

**Comment by upta** [comment]
You rock, Mads!
