### ISSUE TITLE
Support VS 2022

### ISSUE THREAD

**Issue by tiesmaster** [madskristensen/ResetZoom#4]
I know you're very busy with upgrading all your other extensions to VS 2022, and I'm just really grateful that you put that out there. So consider this merely a placeholder issue that I (and maybe others) can watch when you get to this one.

BTW If you appreciate a PR to upgrade this extension, then I'm willing to take a stab at it. Let me know if you're interested, or rather do a change like this yourself.

**Comment by madskristensen** [comment]
The functionality in this extension is now part of the Tweaks extension which has been ported to VS 2022. Can you use that instead?

**Comment by Eagle3386** [comment]
Can't speak for @tiesmaster, but being subscribed due to same interest, I'd rather see Reset Zoom updated for VS 2022 than install your Tweakster extension. Mostly due to having - at most - 3 useful features for my usage scenarios, with 2 of them being either possible via other ways (CTRL + W for closing an editor can be set manually in VS options by any dev & the "Switch to debug window on debug start" one is already offered by VSColorOutput64).

So, I'd like to advocate for a Reset Zoom version for VS 2022.

**Comment by madskristensen** [comment]
Ok

**Comment by tiesmaster** [comment]
@madskristensen Awesome!! Thank you. I think I can you that extension instead. I'll install it now, and close the issue, if it's good enough for me. I don't fully understand the argumentation of @Eagle3386, but if still deems it necessary, then he can reopen the issue.

**Comment by tiesmaster** [comment]
@madskristensen 😮 The Tweaks extension is really awesome!! It's amazing, all the missing things that this extension adds. Unbelievable, I overlooked this extension (then again, you do have a few 😅 ).

**Comment by Eagle3386** [comment]
@tiesmaster I can't reopen your issue as it's you who started it & hence only that person or any repo-owner can reopen it. 😔

Besides, I'd love to see @madskristensen work(flow) simplified by developing the code once, but use it for both, a single Reset Zoom extension & as part of the Tweakers extension.
If that's possible, I'd love to see Reset Zoom updated for VS 2022. If not, I'd probably, reluctantly, switch to Tweakers as changing the zoom level happens - undesirable (!) - too often to not use any shortcut for resetting it back to normal.. 🙈😅

Maybe you, Mads, can convince MS about either integrating a zoom reset menu option which any dev can then freely assign a shortcut if MS doesn't want to define one on their own or at least convince them of providing an option to disable any zooming at all (perhaps via (another) shortcut)? 🤔

**Comment by madskristensen** [comment]
New version uploaded to the Marketplace. It will be ready in a few minutes

**Comment by Eagle3386** [comment]
FWIW: Actually, I already opened a [feature suggestion](https://developercommunity.visualstudio.com/t/Reset-zoom-via-keyboard-shortcut/1373025) over at VS Dev Community back in March this year. So, if people would upvote my suggestion, VS will probably include it by themselves in a next version..
